### ISSUE TITLE
新版的代码高亮如何使用？

### ISSUE THREAD

**Issue by dustofsoul** [imzhengfei/ghost-theme-flatghost#2]

**Comment by imzhengfei** [comment]
@dustofsoul 
感谢提问，很抱歉没有说明使用方法，会在后续的更新中补充说明文档。

在 MD 插入整段代码的**起始标签** ` ``` ` 后面加上**代码类型名称**即可，如：
```
```shell
```
常见的名称如：html, javascript, css, php, java, swift, shell, mysql, nginx... （支持 20+ 常见代码类型）。

如果是使用 html 直接写，在 `pre` 标签里面直接添加名为 `language-xxx` 的类（class）即可，如：
```html
<pre class="language-shell">
  <code>
    <!-- code... -->
  </code>
<pre>
```
**注意：** 只支持整段代码（ `<pre><code></code></pre>` ）方式，不支持行内代码（ `<code></code>` ）方式。
